name: "my action"
description: "test"

inputs:
  message:
    description: "el mensaje a imprimir"
    required: true
    default: "hola"

runs:
  using: "composite"
  steps:
    - name: deploy
      shell: bash   
      run: echo "hola ${{ inputs.message }}"
